resolver: nightly-2025-09-10
system-ghc: true
packages:
  - reflection-base
  - reflection-serialiser
  - reflection-json-parser
  - benchmarks/parser-server/haskell
  - benchmarks/rtt
extra-deps:
  - flatparse-0.5.3.0
