name: reflection-serialiser
version: 0.1.0.0
github: "githubuser/reflection-serialiser"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2025 Author name here"

description: Please see the README on GitHub at <https://github.com/githubuser/reflection-serialiser#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - reflection-base
  - aeson

default-extensions:
  - AllowAmbiguousTypes
  - LambdaCase
  - MultiParamTypeClasses
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - template-haskell
    - containers
  exposed-modules:
    - Data.Reflection.Serialiser
    - Data.Reflection.Serialiser.Format
    - Data.Reflection.Serialiser.Format.JSON
    - Data.Reflection.Serialiser.Format.XML
    - Data.Reflection.Serialiser.FieldName
    - Data.Reflection.Serialiser.Serialisable
    - Data.Reflection.Serialiser.Serialisable.TH
    - Data.Reflection.Serialiser.Serialisable.TH.Internal
    - Data.Reflection.Serialiser.Serialisable.TH.CompiledTemplate
    - Data.Reflection.Serialiser.Template

tests:
  serialiser-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - reflection-serialiser
      - hspec

benchmarks:
  micro:
    main: Main.hs
    source-dirs: benchmark/micro
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-T
      - -O2
      - -Wno-unused-top-binds
      - -Wno-orphans
      - -Wno-redundant-constraints
    dependencies:
      - reflection-serialiser
      - xml
      - criterion
      - aeson
      - bytestring-strict-builder
  servant:
    main: Main.hs
    source-dirs: benchmark/servant
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - reflection-serialiser
      - aeson
      - deepseq
      - servant
      - servant-server
      - warp
      - criterion
      - network-uri
      - HTTP
  pandoc:
    main: Main.hs
    source-dirs: benchmark/pandoc
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - reflection-serialiser
      - aeson
      - deepseq
      - criterion
      - pandoc
      - text
      - pandoc-types
